name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # ✅ latest

      - name: Set up Python
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Jupyter notebook
        run: |
          pip install jupyter
          jupyter nbconvert --to notebook --execute LSTM-CNN.ipynb --output executed_notebook.ipynb

      - name: Upload executed notebook
        uses: actions/upload-artifact@v4   # ✅ updated version
        with:
          name: executed-notebook
          path: executed_notebook.ipynb
